import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// 把 `NSPasteboard` 的当前内容解释成一条 `ClipItem`。
enum PasteboardReader {
    /// 密码管理器等用这些私有类型标记「不要记录我」。这是 nspasteboard.org 的社区约定，
    /// 1Password / Bitwarden / KeePassXC 都遵守。忽略它是剪贴板管理器最基本的义务。
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// 返回 nil 表示这次变更应被忽略（敏感内容、空内容、或来自被排除的 App）。
    static func read(_ pb: NSPasteboard, source: NSRunningApplication?, blobsURL: URL) -> ClipItem? {
        let available = Set((pb.types ?? []).map(\.rawValue))
        guard available.isDisjoint(with: sensitiveTypes) else {
            Log.clipboard.debug("skip: sensitive pasteboard type")
            return nil
        }

        var kind: ClipKind = .text
        var text = ""
        var blobPath: String?
        var meta: String?
        var digestSeed = Data()

        // 顺序即优先级：先文件、再图片，最后才退到文本表示。
        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL], let first = urls.first, first.isFileURL {
            kind = .file
            text = urls.map(\.path).joined(separator: "\n")
            meta = urls.count > 1 ? "\(urls.count) files" : first.deletingLastPathComponent().lastPathComponent + "/"
            digestSeed = Data(text.utf8)
        } else if let image = NSImage(pasteboard: pb),
                  let png = image.pngData() {
            kind = .image
            let name = "\(UUID().uuidString).png"
            try? png.write(to: blobsURL.appendingPathComponent(name))
            blobPath = name
            let size = image.size
            text = ""   // 留给 OCR 填充，见 CLAUDE.md 路线图
            meta = "\(Int(size.width)) × \(Int(size.height))"
            digestSeed = png
        } else if let string = pb.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            text = string
            meta = nil   // 文本类由字符数动态生成，不入库
            digestSeed = Data(string.utf8)
            if let url = URL(string: string.trimmingCharacters(in: .whitespacesAndNewlines)),
               let scheme = url.scheme, ["http", "https"].contains(scheme) {
                kind = .link
            } else if let rtf = pb.data(forType: .rtf) {
                kind = .richText
                let name = "\(UUID().uuidString).rtf"
                try? rtf.write(to: blobsURL.appendingPathComponent(name))
                blobPath = name
            }
        } else {
            return nil
        }

        return ClipItem(
            kind: kind,
            text: text,
            blobPath: blobPath,
            sourceBundleID: source?.bundleIdentifier,
            sourceAppName: source?.localizedName,
            createdAt: Date(),
            meta: meta,
            fingerprint: SHA256.hash(data: digestSeed).map { String(format: "%02x", $0) }.joined()
        )
    }
}

extension NSImage {
    func pngData() -> Data? {
        guard let tiff = tiffRepresentation, let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
